#spring:
#  # session 配置
#  session:
#    # 30 天过期
#    timeout: 2592000
#    store-type: redis
#  # 数据库配置
#  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/codingparnter_db
#    username: root
#    password: 123456
#  # Redis 配置
#  redis:
#    database: 1
#    host: 127.0.0.1
#    port: 6379
#    timeout: 5000
#  servlet:
#    multipart:
#      # 大小限制
#      max-file-size: 10MB
#server:
#  address: 0.0.0.0
#  port: 8181
#  servlet:
#    context-path: /api
#    # cookie 30 天过期
#    session:
#      cookie:
#        max-age: 2592000